### ISSUE TITLE
About entity framework core integration

### ISSUE THREAD

**Issue by rodrigoauglima** [smokedlinq/Microsoft.Azure.WebJobs.Extensions.OData#2]
Sorry for opening an issue, but I have a question: about Entity Framework Core integration, keeping IQueryable without bringing all the data into memory, were you able to implement it?
Thank you for the excellent contribution.

**Comment by smokedlinq** [comment]
Sorry the email notification got swallowed in my inbox. Are you good or still want me to look into this?

**Comment by rodrigoauglima** [comment]
Hello, I change to a manual implementation with Dynamiq Linq for now, because of my schedule. But, it will be great if you could provide some implementation EF Core 3, because the only way I managed to make work was bring all data in DbSet first and then apply oData. In any case, thanks for the help.

**Comment by smokedlinq** [comment]
Sure thing, added an in memory context and it does appear to only return the data that is filtered by the odata query. Give it a try, this should work for you assuming EFCore behaves the same when connected to a real data source.

**Comment by rodrigoauglima** [comment]
Thanks! I've tested here with EF Core and SQL Server, and worked fine, except when we use group by clause. 
I am seing this error:

`Microsoft.AspNet.OData.Query.Expressions.AggregationWrapper' does not match the expected entity type 'app......entity' as set on the query context. (Parameter 'context')'`

For now I wil keep using the other approadh I mentioned before with Dynamic Linq, since we already create some infrastructure to translate the querystring received to the dynamiq linq and the group by, pagination and order by are working.

But if you update this package, and need some help I will try to help. In this week maybe not because of the project schedule.
Thanks again.

**Comment by smokedlinq** [comment]
I dug around, this looks like a limitation on EFCore 3.1 ... doesn't look like it'll be fixed in the 5.0 release either.

https://github.com/dotnet/efcore/issues/20040

**Comment by smokedlinq** [comment]
I was able to get group by to work but not aggregate within it.
